<?php

declare(strict_types=1);

/*
 * PHP-CS-Fixer configuration for the crashler project.
 *
 * Ruleset: @Symfony + @Symfony:risky with a small project-specific override
 * block. Excludes generated and vendored code. See
 * openspec/specs/developer-tooling/spec.md for the contract this implements.
 */

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__)
    ->exclude([
        'var',
        'vendor',
        'tools',
        'migrations',
        'public/bundles',
        'public/assets',
    ])
    ->notPath([
        // Auto-generated by Symfony Flex; content mirrors upstream PHPDoc
        // verbatim, so locally rewriting `@type` to `@var` (etc.) would
        // corrupt it and the next regen would clobber the fix anyway.
        'config/reference.php',
    ])
    ->name('*.php')
    ->notName('*.blade.php')
    ->ignoreDotFiles(true)
    ->ignoreVCS(true);

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,

        // Project-specific overrides:
        // - Always trailing comma in multiline arrays/argument lists
        //   (more diff-friendly).
        'trailing_comma_in_multiline' => [
            'elements' => ['arrays', 'arguments', 'parameters', 'match'],
        ],
        // - Allow single-line throw expressions; the codebase already uses
        //   them throughout (e.g., `?? throw new Exception(...)`).
        'single_line_throw' => false,
        // - Concise array notation everywhere (Symfony preset already does).
        'array_syntax' => ['syntax' => 'short'],
        // - declare(strict_types=1) on every PHP file we author.
        'declare_strict_types' => true,
        // - Phpdoc summary order — match Symfony preset, no extra opinion.
    ])
    ->setFinder($finder)
    ->setCacheFile('.php-cs-fixer.cache');
