<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260509223424 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial identity & tenancy schema: user, org, tenant, memberships, tenant_token, plus messenger_messages.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE org (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              slug VARCHAR(32) NOT NULL,
              name VARCHAR(128) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_org_slug ON org (slug)');
        $this->addSql(<<<'SQL'
            CREATE TABLE org_membership (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              role VARCHAR(16) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_id INT NOT NULL,
              org_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_3A39D41A76ED395 ON org_membership (user_id)');
        $this->addSql('CREATE INDEX IDX_3A39D41F4837C1B ON org_membership (org_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_org_membership_user_org ON org_membership (user_id, org_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE tenant (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              slug VARCHAR(32) NOT NULL,
              name VARCHAR(128) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              org_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_4E59C462F4837C1B ON tenant (org_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tenant_slug ON tenant (slug)');
        $this->addSql(<<<'SQL'
            CREATE TABLE tenant_membership (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              role VARCHAR(16) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_id INT NOT NULL,
              tenant_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_7EBE842DA76ED395 ON tenant_membership (user_id)');
        $this->addSql('CREATE INDEX IDX_7EBE842D9033212A ON tenant_membership (tenant_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_tenant_membership_user_tenant ON tenant_membership (user_id, tenant_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE tenant_token (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(128) NOT NULL,
              hash VARCHAR(64) NOT NULL,
              expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              tenant_id INT NOT NULL,
              created_by_user_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_40A74D0F9033212A ON tenant_token (tenant_id)');
        $this->addSql('CREATE INDEX IDX_40A74D0F7D182D95 ON tenant_token (created_by_user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tenant_token_hash ON tenant_token (hash)');
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(180) NOT NULL,
              email_lower VARCHAR(180) NOT NULL,
              roles JSON NOT NULL,
              password VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email_lower ON "user" (email_lower)');
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              body TEXT NOT NULL,
              headers TEXT NOT NULL,
              queue_name VARCHAR(190) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (
              queue_name, available_at, delivered_at,
              id
            )
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              org_membership
            ADD
              CONSTRAINT FK_3A39D41A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              org_membership
            ADD
              CONSTRAINT FK_3A39D41F4837C1B FOREIGN KEY (org_id) REFERENCES org (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              tenant
            ADD
              CONSTRAINT FK_4E59C462F4837C1B FOREIGN KEY (org_id) REFERENCES org (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              tenant_membership
            ADD
              CONSTRAINT FK_7EBE842DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              tenant_membership
            ADD
              CONSTRAINT FK_7EBE842D9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              tenant_token
            ADD
              CONSTRAINT FK_40A74D0F9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              tenant_token
            ADD
              CONSTRAINT FK_40A74D0F7D182D95 FOREIGN KEY (created_by_user_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE org_membership DROP CONSTRAINT FK_3A39D41A76ED395');
        $this->addSql('ALTER TABLE org_membership DROP CONSTRAINT FK_3A39D41F4837C1B');
        $this->addSql('ALTER TABLE tenant DROP CONSTRAINT FK_4E59C462F4837C1B');
        $this->addSql('ALTER TABLE tenant_membership DROP CONSTRAINT FK_7EBE842DA76ED395');
        $this->addSql('ALTER TABLE tenant_membership DROP CONSTRAINT FK_7EBE842D9033212A');
        $this->addSql('ALTER TABLE tenant_token DROP CONSTRAINT FK_40A74D0F9033212A');
        $this->addSql('ALTER TABLE tenant_token DROP CONSTRAINT FK_40A74D0F7D182D95');
        $this->addSql('DROP TABLE org');
        $this->addSql('DROP TABLE org_membership');
        $this->addSql('DROP TABLE tenant');
        $this->addSql('DROP TABLE tenant_membership');
        $this->addSql('DROP TABLE tenant_token');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
