<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\MariaDBPlatform;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds the `invitation` table for tenant-scoped invitations introduced
 * by add-tenant-self-service-ui. Each invitation grants a TenantMembership
 * on accept; the `accepted_at` / `accepted_by_user_id` columns mark single-
 * use consumption.
 *
 * Partial unique index `(tenant_id, email) WHERE accepted_at IS NULL` is
 * added on Postgres to enforce "one pending invitation per (tenant, email)"
 * at the database level. MariaDB does not support partial unique indexes,
 * so the same invariant is enforced at the service level via
 * InvitationRepository::findPendingByTenantAndEmail() (see Section 7
 * of the change tasks).
 */
final class Version20260510084634 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add invitation table for tenant-scoped self-service invitations.';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();

        if ($platform instanceof PostgreSQLPlatform) {
            $this->upPostgres();

            return;
        }
        if ($platform instanceof MariaDBPlatform) {
            $this->upMariaDb();

            return;
        }
        $this->abortIf(true, \sprintf('Unsupported database platform for this migration: %s', $platform::class));
    }

    public function down(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();

        if ($platform instanceof PostgreSQLPlatform) {
            $this->downPostgres();

            return;
        }
        if ($platform instanceof MariaDBPlatform) {
            $this->downMariaDb();

            return;
        }
        $this->abortIf(true, \sprintf('Unsupported database platform for this migration: %s', $platform::class));
    }

    private function upPostgres(): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE invitation (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(180) NOT NULL,
              role VARCHAR(16) NOT NULL,
              token VARCHAR(64) NOT NULL,
              expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              tenant_id INT NOT NULL,
              created_by_user_id INT NOT NULL,
              accepted_by_user_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_F11D61A29033212A ON invitation (tenant_id)');
        $this->addSql('CREATE INDEX IDX_F11D61A27D182D95 ON invitation (created_by_user_id)');
        $this->addSql('CREATE INDEX IDX_F11D61A2110B274A ON invitation (accepted_by_user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_invitation_token ON invitation (token)');
        // Partial unique index: one pending (un-accepted) invitation per (tenant, email).
        // Re-inviting after acceptance or expiry is allowed.
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_invitation_pending_tenant_email
              ON invitation (tenant_id, email)
              WHERE accepted_at IS NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              invitation
            ADD
              CONSTRAINT FK_F11D61A29033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              invitation
            ADD
              CONSTRAINT FK_F11D61A27D182D95 FOREIGN KEY (created_by_user_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              invitation
            ADD
              CONSTRAINT FK_F11D61A2110B274A FOREIGN KEY (accepted_by_user_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
    }

    private function downPostgres(): void
    {
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A29033212A');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A27D182D95');
        $this->addSql('ALTER TABLE invitation DROP CONSTRAINT FK_F11D61A2110B274A');
        $this->addSql('DROP TABLE invitation');
    }

    private function upMariaDb(): void
    {
        // No partial unique index on MariaDB — pending-uniqueness invariant
        // is enforced at the service level by InvitationRepository.
        $this->addSql(<<<'SQL'
            CREATE TABLE invitation (
              id INT AUTO_INCREMENT NOT NULL,
              email VARCHAR(180) NOT NULL,
              role VARCHAR(16) NOT NULL,
              token VARCHAR(64) NOT NULL,
              expires_at DATETIME NOT NULL,
              created_at DATETIME NOT NULL,
              accepted_at DATETIME DEFAULT NULL,
              tenant_id INT NOT NULL,
              created_by_user_id INT NOT NULL,
              accepted_by_user_id INT DEFAULT NULL,
              INDEX IDX_F11D61A29033212A (tenant_id),
              INDEX IDX_F11D61A27D182D95 (created_by_user_id),
              INDEX IDX_F11D61A2110B274A (accepted_by_user_id),
              UNIQUE INDEX uniq_invitation_token (token),
              PRIMARY KEY (id)
            ) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A29033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A27D182D95 FOREIGN KEY (created_by_user_id) REFERENCES `user` (id) ON DELETE RESTRICT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A2110B274A FOREIGN KEY (accepted_by_user_id) REFERENCES `user` (id) ON DELETE SET NULL
        SQL);
    }

    private function downMariaDb(): void
    {
        $this->addSql('ALTER TABLE invitation DROP FOREIGN KEY FK_F11D61A29033212A');
        $this->addSql('ALTER TABLE invitation DROP FOREIGN KEY FK_F11D61A27D182D95');
        $this->addSql('ALTER TABLE invitation DROP FOREIGN KEY FK_F11D61A2110B274A');
        $this->addSql('DROP TABLE invitation');
    }
}
